package com.acadiainfo.comptatransport.domain;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;

import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * One set of Shipping preferences and conditions applied to a given Customer.
 */
@Entity
@IdClass(CustomerShipPreferences.CompositePK.class)
@Table(schema = "ComptaTransport", name = "CUSTOMER_SHIP_PREFERENCES")
public class CustomerShipPreferences implements Auditable, Comparable<CustomerShipPreferences> {

	public static class CompositePK  implements java.io.Serializable {
		/** (generated by Eclipse) */
		private static final long serialVersionUID = 345741418711584721L;

		private Long customer;
	    private LocalDateTime applicationDate;

	    public CompositePK() {}

	    public CompositePK(Long customer, LocalDateTime applicationDate) {
	        this.customer = customer;
	        this.applicationDate = applicationDate;
	    }

	    @Override
		public int hashCode() {
			return Objects.hash(applicationDate, customer);
		}

		@Override
		public boolean equals(Object obj) {
			if (this == obj) {
				return true;
			}
			if (obj == null) {
				return false;
			}
			if (getClass() != obj.getClass()) {
				return false;
			}
			CompositePK other = (CompositePK) obj;
			return Objects.equals(applicationDate, other.applicationDate) && Objects.equals(customer, other.customer);
		}

		public Long getCustomer() {
			return customer;
		}

		public void setCustomer(Long customer) {
			this.customer = customer;
		}

		public LocalDateTime getApplicationDate() {
			return applicationDate;
		}

		public void setApplicationDate(LocalDateTime applicationDate) {
			this.applicationDate = applicationDate;
		}
	}

	/** Half of PK, FK to parent Customer (cannot be re-attributed) */
	@jakarta.json.bind.annotation.JsonbTransient
	@ManyToOne(fetch = FetchType.EAGER)
	@Id
	@JoinColumn(name = "customer_id", referencedColumnName = "id", nullable = false, updatable = false)
	private Customer customer;

	/** 2nd half of PK, indicates the date at which these conditions are applicable. */
	@Id
	@Column(name = "application_date", nullable = false)
	private LocalDateTime applicationDate;

	/** (optional) FK to customer-specific PriceGrid */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "override_price_grid", nullable = true)
	private PriceGrid overridePriceGrid;

	/** list of "virtual FK" to customer's exclusive Carriers. */
	@Column(name = "override_carriers")
	private Set<String> overrideCarriers = new TreeSet<String>();

	/** Tags referring to Carriers' tags */
	@Column(name = "carrier_tags_whitelist")
	private Set<String> carrierTagsWhitelist = new TreeSet<String>();

	/** Tags can be used for technical filtering (e.g. "Grand Compte") or further description. */
	@Column(name = "carrier_tags_blacklist")
	private Set<String> carrierTagsBlacklist = new TreeSet<String>();

	@Embedded
	private AuditingInfo auditingInfo;


	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public LocalDateTime getApplicationDate() {
		return applicationDate;
	}

	public void setApplicationDate(LocalDateTime applicationDate) {
		this.applicationDate = applicationDate;
	}

	public PriceGrid getOverridePriceGrid() {
		return overridePriceGrid;
	}

	public void setOverridePriceGrid(PriceGrid overridePriceGrid) {
		this.overridePriceGrid = overridePriceGrid;
	}

	public Set<String> getOverrideCarriers() {
		return overrideCarriers;
	}

	public void setOverrideCarriers(Set<String> overrideCarriers) {
		this.overrideCarriers = overrideCarriers;
	}

	public Set<String> getCarrierTagsWhitelist() {
		return carrierTagsWhitelist;
	}

	public void setCarrierTagsWhitelist(Set<String> carrierTagsWhitelist) {
		this.carrierTagsWhitelist = carrierTagsWhitelist;
	}

	public Set<String> getCarrierTagsBlacklist() {
		return carrierTagsBlacklist;
	}

	public void setCarrierTagsBlacklist(Set<String> carrierTagsBlacklist) {
		this.carrierTagsBlacklist = carrierTagsBlacklist;
	}

	@Override
	public AuditingInfo getAuditingInfo() {
		return auditingInfo;
	}

	// as per equality contract, as it is mapped as a Set item by Customer
	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof CustomerShipPreferences)) {
			return false;
		}
		CustomerShipPreferences that = (CustomerShipPreferences) o;
		Long thisCustId = (this.customer == null || this.customer.getId() == null) ? 0L : this.customer.getId();
		Long thatCustId = (that.customer == null || that.customer.getId() == null) ? 0L : that.customer.getId();

		return thisCustId.equals(thatCustId)
		  && applicationDate != null && applicationDate.equals(((CustomerShipPreferences) o).applicationDate);
	}

	@Override
	public int hashCode() {
		if (customer == null || customer.getId() == null) {
			return -1;
		} else {
			return (int) (customer.getId().longValue() % Integer.MAX_VALUE);
		}
	}

	@Override
	public int compareTo(CustomerShipPreferences o) {
		if (this.equals(o)) {
			return 0;
		}

		int custIdDiff = customer.getId().compareTo(o.getCustomer().getId());
		if (custIdDiff != 0) {
			return custIdDiff;
		}

		int appDateDiff = applicationDate.compareTo(o.applicationDate);
		return -appDateDiff; // * -1 => by Date desc
	}
}
