package com.acadiainfo.util;

import jakarta.persistence.PersistenceException;


/**
 * A "business-oriented" PersistenceException, to tell them apart from "technical" ones.
 * 
 * Too bad JPA doesn't have an equivalent of Spring's 
 * DataIntegrityViolationException (...yet ?)
 */
public class DataIntegrityViolationException extends PersistenceException {

	/* Generated by Eclipse IDE */
	private static final long serialVersionUID = 3459328038379350294L;

	public DataIntegrityViolationException() {
		super();
	}

	public DataIntegrityViolationException(String message, Throwable cause) {
		super(message, cause);
	}

	public DataIntegrityViolationException(String message) {
		super(message);
	}

	public DataIntegrityViolationException(Throwable cause) {
		super(cause);
	}
}
